version: '3.8'

services:
  postgres:
    build: .
    environment:
      POSTGRES_PASSWORD: shillelagh123
      POSTGRES_USER: shillelagh
      POSTGRES_DB: shillelagh
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./entrypoint.sh:/usr/local/bin/custom_entrypoint.sh
      - ..:/src
    ports:
      - "12345:5432"
    entrypoint: /usr/local/bin/custom_entrypoint.sh

volumes:
  db_data:
